model_family: phi

# Data configurations
data_path: locuslab/TOFU
split: full  # Always on full data
batch_size: 8
#gradient_accumulation_steps: 4 #Poisson sampling, which is often used in differential privacy algorithms like Opacus, is not compatible with gradient accumulation.
num_epochs: 1

# Training configurations
lr: 5e-5  # Learning rate
max_grad_norm: 1.0  # Gradient clipping for DP
target_epsilon: 0.5  # Target epsilon for DP
target_delta: 1e-12 # Target delta for DP
# Weight decay (for regularization)
weight_decay: 0.01
# Model save configurations
save_dir: checkpoints/BM_dp_opa_FT_on_${split}_data_epoch_${num_epochs}_lr_${lr}_${model_family}_wd_${weight_decay}_delta_${target_delta}_eps_${target_epsilon}

# Seed for reproducibility
seed: 42


